<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\LandingPageRequest;
use Backpack\CRUD\app\Http\Controllers\CrudController;
use Backpack\CRUD\app\Library\CrudPanel\CrudPanelFacade as CRUD;

/**
 * Class LandingPageCrudController
 * @package App\Http\Controllers\Admin
 * @property-read \Backpack\CRUD\app\Library\CrudPanel\CrudPanel $crud
 */
class LandingPageCrudController extends CrudController
{
    use \Backpack\CRUD\app\Http\Controllers\Operations\ListOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\CreateOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\UpdateOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\DeleteOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\ShowOperation;
    use \Backpack\CRUD\app\Http\Controllers\Operations\CloneOperation;

    /**
     * Configure the CrudPanel object. Apply settings to all operations.
     *
     * @return void
     */
    public function setup()
    {
        CRUD::setModel(\App\Models\LandingPage::class);
        CRUD::setRoute(config('backpack.base.route_prefix') . '/page');
        CRUD::setEntityNameStrings('page', 'pages');
    }

    /**
     * Define what happens when the List operation is loaded.
     *
     * @see  https://backpackforlaravel.com/docs/crud-operation-list-entries
     * @return void
     */
    protected function setupListOperation()
    {

        CRUD::column('title');
        CRUD::column('slug');
        CRUD::column('project_id')
            ->type('relationship')
            ->label('Belongs to the Project');
        CRUD::column('active')
            ->label('Published')
            ->type('check');
        CRUD::column('description')
        ->type('textarea');

        /**
         * Columns can be defined using the fluent syntax or array syntax:
         * - CRUD::column('price')->type('number');
         * - CRUD::addColumn(['name' => 'price', 'type' => 'number']);
         */
    }

    /**
     * Define what happens when the Create operation is loaded.
     *
     * @see https://backpackforlaravel.com/docs/crud-operation-create
     * @return void
     */
    protected function setupCreateOperation()
    {
        CRUD::setValidation(LandingPageRequest::class);

        CRUD::field('project')
            ->type('relationship')
            ->label('Belongs to the project');

        CRUD::field('title')->type('text');

        CRUD::field('slug')->type('text')
        ->hint("Will be autogenerated from title if null");

        CRUD::field('product_handle')
            ->label('Handle')
            ->hint("Optional field: If it's a Bundle or Product page, you can inform the handle. So the Frontend can automate the build page");
        CRUD::field('description')
            ->type('textarea')
            ->hint('For Administration control');
        CRUD::field('content')
            ->label('Page Content')
            ->type('ckeditor');
        CRUD::addField([
            'name' => 'active',
            'label' => 'Status',
            'type' => 'radio',
            'options' => [
                0 => 'Draft',
                1 => 'Published'
            ],
            'inline' => true
        ]);

    }

    /**
     * Define what happens when the Update operation is loaded.
     *
     * @see https://backpackforlaravel.com/docs/crud-operation-update
     * @return void
     */
    protected function setupUpdateOperation()
    {
        $this->setupCreateOperation();
    }
}
